#!/usr/bin/env python3

"""
@file waid_08_2_doc_dbt_deploy.py
@brief Automated dbt documentation pipeline and physical SQLite schema inspector.
@details Calculates incremental hashes, triggers dbt docs, parses manifest.json, 
         inspects physical SQLite databases, and outputs a comprehensive Markdown report.
@author AF
@date 2026
"""

import os
import subprocess
import sys
from pathlib import Path
import json
import hashlib
import sqlite3
from loguru import logger

if not os.environ.get("WAID_SOURCE"):
    sys.exit("[CRITICAL] WAID_SOURCE environment variable is missing. Export it first.")

sys.path.append(str(Path(os.environ.get("WAID_SOURCE")) / "config"))
from boot import (
    WaidBoot,
    WError,
    WaidExit,
)

sys.path.append(str(Path(os.environ.get("WAID_SOURCE")) / "src"))
from waid_shared import (
    is_in_docker
)


def calculate_models_hash(dbt_dir: Path) -> str:
    """
    @brief Calculates a cumulative MD5 hash of all .sql and .yml files within the models directory.

    @param dbt_dir Path to the dbt project directory.
    @return Cumulative MD5 hash hex string.
    """
    hasher = hashlib.md5()
    models_dir = dbt_dir / "models"
    
    files = sorted(list(models_dir.rglob("*.sql")) + list(models_dir.rglob("*.yml")))
    
    for file_path in files:
        hasher.update(file_path.read_bytes())
        
    return hasher.hexdigest()


def extract_sqlite_schemas(project_root: Path) -> str:
    """
    @brief Scans for SQLite database files and extracts their tables and column definitions.

    @param project_root Root path of the WAID project.
    @return Markdown formatted string containing SQLite database structures.
    """
    content = "## 🗄️ Physical SQLite Databases & Tables\n\n"
    content += "> Inspected directly from local SQLite database files.\n\n---\n\n"
    
    # Locate potential SQLite files across typical project paths
    db_files = list(project_root.rglob("*.db")) + list(project_root.rglob("*.sqlite"))
    
    if not db_files:
        content += "_No physical SQLite database files found in the workspace._\n\n"
        return content

    for db_path in sorted(set(db_files)):
        # Skip temporary or target build artifacts if needed
        if "target" in db_path.parts or ".dbt" in db_path.parts:
            continue
            
        try:
            rel_path = db_path.relative_to(project_root)
        except ValueError:
            rel_path = db_path

        content += f"### 📁 Database File: `{rel_path}`\n\n"
        try:
            conn = sqlite3.connect(str(db_path))
            cursor = conn.cursor()
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name;")
            tables = cursor.fetchall()
            
            if not tables:
                content += "_No user tables found in this database._\n\n"
                conn.close()
                continue

            for (table_name,) in tables:
                content += f"#### Table: `{table_name}`\n\n"
                content += "| Column | Type | NotNull | Default | PK |\n"
                content += "| :--- | :--- | :--- | :--- | :--- |\n"
                
                # Use double quotes for table identifier escaping
                cursor.execute(f'PRAGMA table_info("{table_name}")')
                columns = cursor.fetchall()
                for col in columns:
                    col_name = col[1]
                    col_type = col[2] or "ANY"
                    not_null = "YES" if col[3] == 1 else "NO"
                    default_val = str(col[4]) if col[4] is not None else "-"
                    pk = "YES" if col[5] > 0 else "NO"
                    content += f"| **{col_name}** | `{col_type}` | {not_null} | {default_val} | {pk} |\n"
                
                content += "\n"
            conn.close()
        except Exception as exc:
            content += f"> **Error inspecting database:** `{exc}`\n\n"
            
        content += "---\n\n"
        
    return content


def extract_and_generate_markdown(manifest_path: Path, output_file: Path, project_root: Path) -> None:
    """
    @brief Reads dbt manifest.json and physical SQLite files to generate a unified Markdown documentation report.

    @param manifest_path Path to manifest.json generated by dbt.
    @param output_file Target Path where the Markdown documentation will be written.
    @param project_root Root path of the WAID project for SQLite scanning.
    @raises WError If the manifest.json file is not found.
    """
    try:
        with open(manifest_path, "r", encoding="utf-8") as f:
            manifest = json.load(f)
    except FileNotFoundError:
        raise WError(f"Manifest not found at {manifest_path}. Execute 'dbt compile' first.", WaidExit.INPUT_FAIL)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("# 📊 WAID Data Architecture & Models Documentation\n\n")
        f.write("> Automatically generated report from dbt `manifest.json` and physical SQLite inspection.\n\n---\n\n")
        
        # 1. dbt Models Section
        f.write("## 🏗️ dbt Transform Models\n\n")
        for node_id, node_data in manifest.get("nodes", {}).items():
            if node_data.get("resource_type") == "model":
                f.write(f"### Model: `{node_data.get('name')}`\n\n")
                f.write(f"**Schema:** `{node_data.get('schema')}`  \n")
                f.write(f"**Description:** {node_data.get('description', 'No description available.')}\n\n")
                
                f.write("| Column | Data Type | Description |\n")
                f.write("| :--- | :--- | :--- |\n")
                
                columns = node_data.get("columns", {})
                for col_name, col_data in columns.items():
                    dtype = col_data.get("data_type", "N/A")
                    desc = col_data.get("description", "-")
                    f.write(f"| **{col_name}** | `{dtype}` | {desc} |\n")
                
                f.write("\n---\n\n")
        
        # 2. Physical SQLite Databases Section
        sqlite_markdown = extract_sqlite_schemas(project_root)
        f.write(sqlite_markdown)
                
    logger.info(f"✅ Comprehensive Markdown documentation successfully generated: {output_file}")


def check_and_complete() -> None: 
    """
    @brief Verifies that the generated Markdown documentation exists and provides local preview instructions.
    """
    doc_file = Path("docs/waid_dbt_models.md")
    if doc_file.exists():
        logger.info(f"Verification successful: Found generated documentation at {doc_file}")
    else:
        logger.warning(f"Verification warning: Expected documentation file not found at {doc_file}")

    logger.info(
        "To view the dbt docs locally, run: "
        "python3 -m http.server 8080 --directory dbt/target"
    )


def main() -> int:
    """
    @brief Main entry point for documentation generation, dbt parsing, and database inspection.

    @return Execution status code.
    """
    try:
        env = WaidBoot()
        logger.info("Initializing comprehensive documentation generation pipeline...")

        dbt_dir = Path(env.dbt_dir).resolve()
        project_root = Path(env.waid_source_dir).resolve()
        profiles_dir = Path(getattr(env, "config_dir", project_root / "config")).resolve()

        if is_in_docker():
            docs_dir = Path("/tmp/docs")
        else:
            docs_dir = env.docs_dir

        docs_dir.mkdir(parents=True, exist_ok=True)
        markdown_output = docs_dir / "waid_dbt_models.md"
        hash_file = docs_dir / ".dbt_models.hash"
        
        current_models_hash = calculate_models_hash(dbt_dir)
        
        target_dir = dbt_dir / "target" if (dbt_dir / "target" / "manifest.json").exists() else Path("/tmp/dbt_runtime/target")
        manifest_path = target_dir / "manifest.json"
        
        dbt_cmd = [
            str(env.dbt_bin), "docs", "generate", "--profiles-dir", str(profiles_dir), "--project-dir", str(dbt_dir)
        ]
        
        logger.info(f"Executing: {' '.join(dbt_cmd)}")
        result = subprocess.run(dbt_cmd, env=os.environ.copy(), check=False)
        if result.returncode != 0:
            logger.warning("dbt docs generate returned non-zero, proceeding with available manifest or fallback.")

        # Generate combined markdown including dbt nodes and SQLite physical tables
        extract_and_generate_markdown(manifest_path, markdown_output, project_root)
        hash_file.write_text(current_models_hash)

        check_and_complete()
        
        logger.success("Documentation pipeline completed successfully.")
        return WaidExit.SUCCESS

    except WError as err:
        logger.error(f"Pipeline error: {err}")
        return WaidExit.INPUT_FAIL
    except Exception as exc:
        logger.exception(f"Unexpected execution failure: {exc}")
        return WaidExit.CRITICAL_FAIL


if __name__ == "__main__":
    sys.exit(main())