#!/usr/bin/env python3

"""
@file waid_08_3_doc_dbt_deploy.py
@brief Automated dbt documentation pipeline and Markdown report generator.
@details Calculates an incremental hash over dbt model files to detect changes,
         triggers dbt docs generation, parses manifest.json, and outputs a 
         structured Markdown documentation report.
@author AF
@date 2026
"""

import os
import subprocess
import sys
from pathlib import Path
import json
import hashlib

from loguru import logger

# Inject configuration path safely
SYS_PROJECT_ROOT = Path(
    os.environ.get("WAID_SOURCE", Path(__file__).resolve().parents[2])
).resolve()
sys.path.append(str(SYS_PROJECT_ROOT / "config"))

from boot import WError, WaidBoot, WaidExit  # noqa: E402

def calculate_models_hash(dbt_dir: Path) -> str:
    """
    Calculates a cumulative MD5 hash of all .sql and .yml files within the models directory.

    @param dbt_dir Path to the dbt project directory.
    @return Cumulative MD5 hash hex string.
    """
    hasher = hashlib.md5()
    models_dir = dbt_dir / "models"
    
    # Collect all .sql and .yml files and sort them for consistency
    files = sorted(list(models_dir.rglob("*.sql")) + list(models_dir.rglob("*.yml")))
    
    for file_path in files:
        hasher.update(file_path.read_bytes())
        
    return hasher.hexdigest()

def extract_and_generate_markdown(manifest_path: Path, output_file: Path) -> None:
    """
    Reads the compiled dbt manifest.json file and generates a structured Markdown report.

    @param manifest_path Path to manifest.json generated by dbt.
    @param output_file Target Path where the Markdown documentation will be written.
    """
    try:
        with open(manifest_path, "r", encoding="utf-8") as f:
            manifest = json.load(f)
    except FileNotFoundError:
        raise WError(f"Manifest not found at {manifest_path}. Execute 'dbt compile' first.", WaidExit.FILE_NOT_FOUND)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("# 📊 dbt Models Documentation\n\n")
        f.write("> Automatically generated report from dbt `manifest.json`.\n\n---\n\n")
        
        for node_id, node_data in manifest.get("nodes", {}).items():
            if node_data.get("resource_type") == "model":
                f.write(f"## 🏗️ Model: `{node_data.get('name')}`\n\n")
                f.write(f"**Schema:** `{node_data.get('schema')}`  \n")
                f.write(f"**Description:** {node_data.get('description', 'No description available.')}\n\n")
                
                f.write("| Column | Data Type | Description |\n")
                f.write("| :--- | :--- | :--- |\n")
                
                columns = node_data.get("columns", {})
                for col_name, col_data in columns.items():
                    dtype = col_data.get("data_type", "N/A")
                    desc = col_data.get("description", "-")
                    f.write(f"| **{col_name}** | `{dtype}` | {desc} |\n")
                
                f.write("\n---\n\n")
                
    logger.info(f"✅ Markdown documentation successfully generated: {output_file}")


def check_and_complete() -> None: 
    """
    Verifies that the generated Markdown documentation exists and provides local preview instructions.
    """
    # Check actual file inside docs directory
    doc_file = Path("docs/waid_dbt_models.md")
    if doc_file.exists():
        logger.info(f"Verification successful: Found generated documentation at {doc_file}")
    else:
        logger.warning(f"Verification warning: Expected documentation file not found at {doc_file}")

    logger.info(
        "To view the dbt docs locally, run: "
        "python3 -m http.server 8080 --directory dbt/target"
    )
    
    
def main() -> int:
    """
    Main entry point for dbt documentation generation and state tracking.

    @return Execution status code.
    """
    try:
        env = WaidBoot()
        logger.info("Initializing dbt documentation generation pipeline...")

        dbt_dir = Path(env.dbt_dir).resolve()
        profiles_dir = Path(getattr(env, "config_dir", SYS_PROJECT_ROOT / "config")).resolve()

        # Output paths
        docs_dir = SYS_PROJECT_ROOT / "docs"
        docs_dir.mkdir(parents=True, exist_ok=True)
        markdown_output = docs_dir / "waid_dbt_models.md"
        hash_file = docs_dir / ".dbt_models.hash"
        
        # 1. CHECK: Calculate models hash
        current_models_hash = calculate_models_hash(dbt_dir)
        last_models_hash = hash_file.read_text() if hash_file.exists() else None
        
        if current_models_hash == last_models_hash:
            logger.info("No changes detected in dbt models. Skipping generation.")
        else:
            # 2. Execute dbt docs generate
            manifest_path = dbt_dir / "target" / "manifest.json"
            dbt_cmd = ["dbt", "docs", "generate", "--profiles-dir", str(profiles_dir), "--project-dir", str(dbt_dir)]
            
            logger.info(f"Executing: {' '.join(dbt_cmd)}")
            result = subprocess.run(dbt_cmd, env=os.environ.copy(), check=False)
            if result.returncode != 0:
                raise WError("dbt docs generate failed", WaidExit.INTERNAL_ERROR)

            # 3. Generate and check new markdown
            extract_and_generate_markdown(manifest_path, markdown_output)
            
            # 4. Update stored hash
            hash_file.write_text(current_models_hash)

        # 5. Check current dbt doc
        check_and_complete()
        
        logger.success("dbt documentation pipeline completed successfully.")
        return WaidExit.SUCCESS

    except WError as err:
        logger.error(f"Pipeline error: {err}")
        return WaidExit.INPUT_FAIL
    except Exception as exc:
        logger.exception(f"Unexpected execution failure: {exc}")
        return WaidExit.CRITICAL_FAIL

if __name__ == "__main__":
    sys.exit(main())